### ISSUE TITLE
Customizable folders in garage would be nice

### ISSUE THREAD

**Issue by Maqquan** [EmilyBjoerk/lsml#124]
My partial OCD wants the ability to create customized folders for mechs in my garage. I would for example want a "Favourite mechs" an "Experimental builds", maybe "Company chassis", "Arena duel builds" and so on.

**Comment by Zesaric** [comment]
I also would greatly appreciate being able to re-order my mechs via drag and drop and I am delighted to hear it's planned for 2.0! :) Thanks and keep up the great work!
