### ISSUE TITLE
build unreleased mechs

### ISSUE THREAD

**Issue by blackraven1425** [EmilyBjoerk/lsml#149]
I'm not sure exactly how this should be handled, but it would be nice to be able to build mechs that are not yet in the game, but whose stats have been released, like the Phoenix variant mechs.

Idea for how:

1) build in an ability to read a hand-built XML file similar to the one used for mechs from the game, and package it with releases

2) add a menu option for a user to create a new mech layout in detail, which can be used to generate the file from 1

**Comment by EmilyBjoerk** [comment]
I have decided that this feature is outside of the scope for LSML and will not be implemented as it is now.
