### ISSUE TITLE
Cost reference and calculation

### ISSUE THREAD

**Issue by dogfuntom** [EmilyBjoerk/lsml#186]
Oddly but half of cases when I look at reference table is to check price of some item. I'm using Smurfy now but it would be cool if Li Song will show it too.

Also cost calculations is interesting too when you are planning new builds. Especially would be cool to calculate cost of changing your load-out from old to new of the same chassis.

**Comment by EmilyBjoerk** [comment]
The webbased API seems to have gone down the drain. Also I don't feel that cost calculation is within the scope of LSML and if required can easily be checked by exporting to smurfy.
