### ISSUE TITLE
Quickbuttons to change equipped engine size

### ISSUE THREAD

**Issue by Maqquan** [EmilyBjoerk/lsml#197]
It would be nifty if there were up and down arrows in an equipped engine that stepped up or down to the next avaliable engine size, without loosing heatsinkes placed in the engine. Often you want that extra ton of ammo or an extra medium laser just for fun, and then this way of quickly changing engine for tons would come in very handy.

**Comment by EmilyBjoerk** [comment]
This will be indirectly implemented by in issue #392. I'm closing this issue.
