### ISSUE TITLE
Heat+Damage over Time graph

### ISSUE THREAD

**Issue by vetall812** [EmilyBjoerk/lsml#238]
Would you please add graph that have to Y axes - heat (from 0 to 100 %) and damage (from 0 to ... ) per time.

So we can see at what time we stop making maximum damage and need to cease fire from weapons.

PS. It was nice to see you ingame. And you made a wonderful tool.

**Comment by LiSongMWO** [comment]
Could you please elaborate? The time to overheat shows how long you can do
max dps. What would this graph add?

**Comment by LiSongMWO** [comment]
What firing pattern is it? chain fire? everything as often as possible? or
only full alphas? the pattern also depends on weapon groups if chainfiring.

Okay so I get roughly what you want I'm still not sure what it would tell
you and how it would affect how you play the mech?

I have many features left to implement and I'm not opposed to doing this
infact I think it's cool. But you need to convince me it's more important
than other features on my list before I can prioritize this. :)

**Comment by vetall812** [comment]
Plz put it in the bottom of the feature queue. =) I just like to see how
and when i can shoot.

**Comment by EmilyBjoerk** [comment]
I have decided to not implement this. 

Motivation: The graph will not influence the design of a loadout more than currently existing stats already do. It will provide no additional information besides "cool". 

As such, although a cool graph, I deem it too much work for too little gain. If some one is willing to contribute a patch I will accept it but this is not something I feel I can prioritise my time on.
