### ISSUE TITLE
[Request] Cooling ratio breakdown

### ISSUE THREAD

**Issue by evilC** [EmilyBjoerk/lsml#243]
Would it be possible to split out the information for the cooling ratio?

eg, I have 2PPC and 2SRM6 on a mech. I am unlikely to be using both at once - so I would like to see the cooling efficiency for each.
Some way to split out the info would be nice, but I can imagine it would not be easy to fit into the UI without serious changes.

How about a tooltip for the efficiency that shows the efficiency for each kind of weapon separated out?)

**Comment by evilC** [comment]
How about this for an idea?
The current technique I obviously have to use to get this info is to take
some of the weapons off, then look at the heat eff. Why not just simplify
this procedure?
Add a UI element that behaves sort of like a trash can - you can drag items
to it and they sit there.
Each item has a button that when clicked _returns the item to where it came
from_.
This could also improve usability generally - when a user is building a
mech and deciding what to put on it, they could also use this "bin" to hold
the stuff they plan to put on the mech.

**Comment by EmilyBjoerk** [comment]
This issue will be solved by #275. I'm closing this.
