### ISSUE TITLE
Incorrect heat capacity/Time to overheat values with heat containment skill

### ISSUE THREAD

**Issue by NavidA1** [EmilyBjoerk/lsml#381]
LSML version: 1.6.4

https://github.com/EmilyBjoerk/lsml/releases/tag/1.6.4

Steps to reproduce:
1- create this build in LSML: http://mwo.smurfy-net.de/mechlab#i=171&l=6f348e0337f2c23236cedb4ace93b6eef17043bc in LSML
2- Check Cool run, heat containment and double basics skills

The heatcap and time to overheat are displayed as: Heat cap: 69.8 - Time t overheat: 4.8 s

The expected values for the same parameters are: Heat cap: 83.52 - Time to over heat: 7 s

Thank you for this great application.

**Comment by EmilyBjoerk** [comment]
What do you base these expected values on? I need to see a break down to
determine what is wrong.

2015-01-13 7:35 GMT+01:00 NavidA1 <notifications@github.com>:

**Comment by NavidA1** [comment]
The values are based on Smurfy mechlab.

The heat containment mech skill should increase the heat capacity of the mech (engine and heat sinks) by 10% (20% with double basics).

The base heat cap value for that build for example is 69.6 (engine 300 (10DHS) + 14 DHS) which is correctly calculated in LSML.

However, heat containment skill in LSML increases it to 69.7 (69.7 = 69.6 + 0.1   <10/100 increase> ) instead of 76.56 ( 76.56 = 1.1 * 69.6    <10% increase> )

Also, with double basics LSML returns 69.8 (69.7 = 69.6 + 0.2   <20/100 increase> ) instead of 83.52 ( 83.52 = 69.6 * 1.2    <20% pecent increase> )

This gives also an incorrect Time to shut down, as it is dependent on heat cap.

**Comment by EmilyBjoerk** [comment]
I see what's wrong now. Another bug that snuck in while I did the rework
for quirks. Thanks.

2015-01-13 20:30 GMT+01:00 NavidA1 <notifications@github.com>:
