### ISSUE TITLE
Clan CT not visible in compact mode, even with non-fixed slots

### ISSUE THREAD

**Issue by Dauphni** [EmilyBjoerk/lsml#382]
Several clan Mechs have center torso slots that are not fixed, and therefore editable. In normal mode this works fine, but in compact mode the entire CT is considered fixed and therefore hidden, so making changes becomes troublesome.

**Comment by EmilyBjoerk** [comment]
I'll get that fixed for the next release.

2015-01-28 1:44 GMT+01:00 Dauphni <notifications@github.com>:
