### ISSUE TITLE
Current mech silhouette beneath left arm

### ISSUE THREAD

**Issue by trlababalan** [EmilyBjoerk/lsml#387]
I don't know how some chassis look or where their weapon hardpoints are. Some mechs seem great "on paper" while they're bad in-game. 

Having a mech image or just an outline would be of much help. Especially if the hardpoint locations would be marked with dots or X's.

Consumable Modules are beneath the right arm. This information could be beneath the left one.

Edit: There are accurate mech images on Smurfy's website and snafets.de/mwo. Are there any real legal issues in just copy-pasting any of those into the LSML?

**Comment by EmilyBjoerk** [comment]
This is a feature that has been requested before, and is something I might consider doing when I have enough free time. Although it will  just be the same images as you see in the ingame mechlab listing of mechs.

Marking the hardpoint locations requires some serious parsing of the 3D models and rendering them or manual adjustment of the images. I will not introduce any data that requires me to manually keep data up-to-date as this is too time consuming. Parsing the 3D models is also a lot of work to get right and I don't have time to do that. So this will probably not happen unless some one contributes the code for it. 

Smurfy is using the images from the data files, I can probably parse them as well but I have no existing infrastructure to handle non-text (values) data such as images so this is again some work involved.

**Comment by EmilyBjoerk** [comment]
Superseded by #398.
