### ISSUE TITLE
Interactive fields on equipment pieces

### ISSUE THREAD

**Issue by trlababalan** [EmilyBjoerk/lsml#388]
This "issue" was previously called "More UI interaction and selective ghost heat". I've edited this into three separate ones for planning purposes. For reference; "Selective Ghost Heat" is #386 and clicking makes use of #389. 

How hard would it be to make several invisible interactive fields on one equipment icon? Once this is done, more features could be added over the following versions of the LSML.

Examples:
- Mouseover the left side of a <Medium Laser> would show it's HP, destroyed chance, etc. (as it is now)
- Mouseover the right side would show the information that shows on the bottom-left (the bottom-left information is for the last clicked equipment in the left menu).
- Clicking the left side would offer possible replacements of the same type for this equipment
- Clicking the right side would include/exclude this weapon in ghost heat calculations
- Heatsink slots on the engines would be clickable for adding/removing heatsinks.

**Comment by EmilyBjoerk** [comment]
I do not believe that having different effects on different parts of the item is a good idea. There is no indication to the user that this is possible and it is un-intuitive to a new user. 

But some of the ideas are useful so here is what I will do:

* I will add more info to the tooltip on items.
* I will add a right click menu on items with some actions like, remove/upgrade/downgrade/add engine heatsink etc.

**Comment by EmilyBjoerk** [comment]
This has resulted in issue #392. I'm closing this issue.
