### ISSUE TITLE
Clickable equipment pieces

### ISSUE THREAD

**Issue by trlababalan** [EmilyBjoerk/lsml#389]
This "issue" was previously called "More UI interaction and selective ghost heat". I've edited this into three separate ones for planning purposes. For reference; "Selective Ghost Heat" is #386.

I have recently found out that we can use right-click in the Li Song Mechlab. It's for allowing automatic armor adjustment on a component. What a great find! Here are some possibilities for this feature once it's implemented:
- Right-clicking an equipment piece would offer possible replacements of the same type for it
- Left-clicking it would include/exclude this weapon from the ghost heat calculations
- Clicking the left-bottom of an engine would add a Heatsink, right-bottom would remove it.

**Comment by EmilyBjoerk** [comment]
This has resulted in issue #392. I'm closing this issue.
