### ISSUE TITLE
Drop Deck Garage

### ISSUE THREAD

**Issue by xsimonsaysx** [EmilyBjoerk/lsml#396]
Don't know if anyone else is like me or not, but how about a drop deck tab so you can make multiple decks and switch them in game at a glance.

**Comment by EmilyBjoerk** [comment]
Please do take some time to properly describe what you want in more detail
and how it would work. I'm not a mind reader :)

I'm guessing that you want to be able to upload a drop deck from lsml to
your game client?

Pgi has promised an api to upload loadouts etc to the game but this was
about two years ago or so and nothing has been done about it AFAIK.

So to my knowledge it is not currently possible to in any way affect in
game loadouts or drop decks etc from any third party software. So what
you're asking for can't be done unless Pgi gets their thumbs out and
implements the api they promised.

**Comment by xsimonsaysx** [comment]
Yeah sorry...was a quick post earlier....really what I'm thinking is more gimmicky than anything.

I simply think it would be nice feature to have a drop deck tab so if say I have a deck in game that runs a Timberwolf and 3 crows I can save that deck in lsml.  Later I make a deck that I like with 2 hellbringers and 2 crows so I move those in lsml to my drop deck garage.  Now if I want to switch back to my first deck I can quickly look in lsml to remember which variants I used and reload it in game easily.  

For me anyhow it would be a useful feature as I like to try new combinations out frequently, but don't always remember which ones worked the best together.  If it included some sort of tonnage descripter as well on the folder info it may even help new players build their decks outside of game so they aren't switching mechs back and forth in game to find an optimal loadout.

I.E.:   +Clan Deck 1
                 Timberwolf C
                  Crow A
                  Crow B
                  Crow Prime
          +Clan Deck 2
                   HBR
                   HBR
                   Crow
                   Crow
            +IS Deck 1
....................Etc.   Not really looking for any load to game option, although that would be very nice.
