### ISSUE TITLE
Can't change omnipods

### ISSUE THREAD

**Issue by NoriSilverrage** [EmilyBjoerk/lsml#407]
I seem unable to change omnipods on any clan mechs.
LSML version: 1.6.7

Steps to reproduce:
1. Win 7 x64/Java 8 update 60 (64bit/32bit)
2. Pick any clan mech
3. Attempt to change omnipod

Actual result:
Weapons/equipment is removed, but the pod/hardpoints don't change.

Notes:
I've tried this on two different computers with both 32bit and 64bit version of java. I also tried on a computer without MWO installed and another one with (the one with does have the PTS installed).

**Comment by EmilyBjoerk** [comment]
Thank you for reporting this, I will put out a fix ASAP.

2015-09-22 21:59 GMT+02:00 Nori Silverrage <notifications@github.com>:
