### ISSUE TITLE
New loyalty mech variants are not listed in the IS/Clan list

### ISSUE THREAD

**Issue by NavidA1** [EmilyBjoerk/lsml#431]
The following loyalty mech variants:
EXE-C (L)
NVA-D (L)
WVR-7D (L)
CDA-3F (L)
ZEU-9S2 (L)
Are not listed under IS/clan list

**Comment by EmilyBjoerk** [comment]
Quick fix: Go to "Program -> Settings" in LSML. Uncheck "Hide mech variations".

The loyalty mechs are special variants of mechs that (I think should?) be released as normal mechs. Much like KGC-000(L), AS-7S(L) etc.
