### ISSUE TITLE
Game file parse failed

### ISSUE THREAD

**Issue by Dauphni** [EmilyBjoerk/lsml#444]
LSML version: 1.7.1

Since the last patch (1 Dec) I'm getting the game file parse failed error on startup. I'm guessing PGI changed things around again with the new quirks?

EDIT: Interestingly, the new values appear to have updated properly, yet the error persists on startup.

**Comment by EmilyBjoerk** [comment]
I do not get any error. Please open LSML and go to `Program -> Preferences` and make sure that the  correct path to your game is given under `Game Install:`. Please make sure it is not your PTS install.

**Comment by Dauphni** [comment]
It is pointing to the correct path, so that's not it.

Unrelated, but I did notice a typo on one of the checkboxes in the settings window, it reads "Automatically check for udpates"

**Comment by EmilyBjoerk** [comment]
First, lets make sure it's not because some one else is keeping the file
open. Reboot your computer and see if the issue persists.

If it does, can you post the whole error message please?

2015-12-04 18:16 GMT+01:00 Dauphni <notifications@github.com>:

**Comment by Dauphni** [comment]
Rebooted and the issue persists.

The error box reads:
"Reading the game files failed. This is most likely due to changes in the last patch.

LSML will still function with data from the last successful parse.
Please update LSML to the latest version to be sure you have the latest game data."

**Comment by EmilyBjoerk** [comment]
Open file explorer and go to where you installed LSML. Hold left shift and
right click on empty space, select "Open command window here..." then type
"lsml.exe" and hit enter. You should get some more messages.

2015-12-04 18:31 GMT+01:00 Dauphni <notifications@github.com>:

**Comment by Dauphni** [comment]
I tried that, and I'm not seeing anything different. I'm using Windows 10, if that matters.

**Comment by Question2** [comment]
I'm getting the same error when i open the latest version as well.

**Comment by EmilyBjoerk** [comment]
Okay open file explorer and type "%appdata%" into the path field. (should go to `C:\users\your user\AppData\Roaming\`)

Take the `lsml_datacache.xml` and `lsml_settings.xml` files, zip them up and send them to me. Then remove both and see if that fixes your problem.

**Comment by Dauphni** [comment]
That fixed it! Unfortunately Github isn't letting me upload the zip file, but I think I found the problem anyway.

I changed my windows profile name a few months ago, but the gameDataCache entry in lsmlsettings.xml still had the old name in the path, so it pointed to a file that doesn't exist anymore.
Restoring the old files and fixing the gameDataCache path made it work as it should.

**Comment by EmilyBjoerk** [comment]
You can email it to lisongmechlab@gmail.com.

**Comment by EmilyBjoerk** [comment]
Okay I will fix the loading code so that it will not barf if it can't open the old gameDataCache.

**Comment by Question2** [comment]
I dont have a cache file for some reason, but my settings file is :

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>Written by LSML</comment>
<entry key="uiHideSpecialMechs">true</entry>
<entry key="gameDataCache">C:\Users\Question\AppData\Roaming\lsml_datacache.xml</entry>
<entry key="updateCheckEnabled">false</entry>
<entry key="fontSize">Normal</entry>
<entry key="garagefile">C:\Users\Question\Documents\stalker.xml</entry>
<entry key="updateLastCheck">12/5/15 12:47 AM</entry>
<entry key="gamedir">D:\MWO\MechWarrior Online</entry>
</properties>

Deleting the settings file doesnt solve the problem, it still complains that it cannot read the game files because of a patch.

**Comment by EmilyBjoerk** [comment]
@Question2 parsing works fine for me in 1.7.1. Are you using the latest version? Is the game dir correct? Try creating an empty text file as `C:\Users\Question\AppData\Roaming\lsml_datacache.xml` see if it has any effect.

**Comment by EmilyBjoerk** [comment]
@Question2 as I haven't had any reply from you I'm assuming your issue has resolved itself. If you still have problems, please open a new issue.
