### ISSUE TITLE
Drop Ship Issue

### ISSUE THREAD

**Issue by Smokey2** [EmilyBjoerk/lsml#445]
When you remove a mech from the drop ship it gets removed from the garage as well. Gone.

**Comment by EmilyBjoerk** [comment]
When you move a mech to the drop ship it is MOVED from the garage to the drop ship. When you remove if from the drop ship. If you want to keep a copy of the mech in the drop ship, simply hold ctrl when you move the mech there (same as in all windows programs).

**Comment by Smokey2** [comment]
Maybe it should have a “Return to Garage” button.

**Comment by EmilyBjoerk** [comment]
I can add that to the next version. 

For now, hold ctrl if you want to keep a copy. If you want to take a copy of a mech in a drop ship and add it to the garage, open it from the drop ship, clone it and save the clone.
