### ISSUE TITLE
LSML - Smurfy interoperability broken

### ISSUE THREAD

**Issue by EmilyBjoerk** [EmilyBjoerk/lsml#447]
@smurfy It has been brought to my attention that some time between Thursday (10th of December) and Saturday (12th of December) the LSML links from Smurfy started causing errors in LSML. 

I have verified that my unit tests are still able to decode all of the stock loadouts from long before Thursday, I'm also able to encode and decode other loadouts. So I don't think it's on my side, have you changed anything as of late?

**Comment by smurfy** [comment]
I noticed errors with todays error as-well. 
Will disable the links and investigate. I did no intensional change or another i could think of which would change something.

90% of my time spend on the site goes to my complete mechlab rewrite.

**Comment by EmilyBjoerk** [comment]
@smurfy If you need help let me know. I know that I pushed my 1.7.1 update and the links worked (because I did a demo for a friend) then a few days later they weren't working.. :\

**Comment by EmilyBjoerk** [comment]
@smurfy I did some testing, for one of the loadouts which fails the error was caused by a UI bug on my side (triggered when the front/back armor ratio was larger than 16) I have fixed this and ninja injected the fix into 1.7.2. Can you download 1.7.2 and verify some links?

**Comment by EmilyBjoerk** [comment]
Okay so the one link I had from before you turned the links of now works... But I haven't changed anything in that particular piece of code so this issue has to have existed since the beginning. I'm flummoxed as to why it hasn't been discovered earlier. And I'm also wondering if this was all that needed fixing...

**Comment by EmilyBjoerk** [comment]
@smurfy Whats the status on your end? I have user asking me when the interoperability will be back.

**Comment by smurfy** [comment]
Found one problem. 
But this is related to IIC mechs. (I handled them like clan mechs in the lsml creation while i should use the IS variant)

I will rollout the new version in around 30 Minutes If the problem is still there, please give me some examples of corrupt links. (Link to my site and if possible the correct lsml link)

The new version will also store the lsml link to the database instead of recreating it every time, which takes quite long.

**Comment by EmilyBjoerk** [comment]
Okay, I will keep my eyes open. 

Yeah I don't differentiate between IS/Clan, I use Omni/Standard mech instead. I guess that was the cause?

**Comment by EmilyBjoerk** [comment]
I'll close this issue for now. I'll re-open if the issue re-surfaces.
