### ISSUE TITLE
Steamversion

### ISSUE THREAD

**Issue by WarWolfen** [EmilyBjoerk/lsml#448]
It seems that LSML does not work well if given the path to a Steam install. It keeps complaining that there was no valid install in that folder. Seems that there are some differences between the standalone client and the steam installation.

As I have both versions installed just now, I can confirm that it works on one while it is giving errors on the other.

**Comment by EmilyBjoerk** [comment]
I'll look into it next week, I'm hospitalised for the moment.

**Comment by WarWolfen** [comment]
All the best, recover well.
