### ISSUE TITLE
XL Engine sides should be placed as the first item always.

### ISSUE THREAD

**Issue by EmilyBjoerk** [EmilyBjoerk/lsml#471]
When adding an XL engine, the sides are added as regular items and thus may appear below other equipped items. This should be changes so that adding an XL engine, the sides should always be added as the first item in the equipped items list.

**Comment by Zesaric** [comment]
Yes, that would be nice, I absolutely second that idea. To match this, maybe this concept should be applied to engines in general, i.e. making sure that also the CT lists the engine as the topmost item.
