### ISSUE TITLE
Cycle Times are Off

### ISSUE THREAD

**Issue by crazy6432** [EmilyBjoerk/lsml#480]
Comparing to Smurfy and the game's XML files, the cycle times for clan autocannons are off (both ultra and regulars). I haven't checked every weapon, so other weapon types may also be off.

**Comment by EmilyBjoerk** [comment]
The cycle times for clan ac weapons include the time between each of the
clan ac rounds in one shot. For ultra ac weapons the cycle time is the
average cycle time taking double fire, jam chance and jam time into
account. If you are looking on the info under the equipment list, this also
includes your quirks, pilot skills and modules.

Please note that cooldown isn't cycletime. For example for lasers the cycle
time is cooldown + burntime.

**Comment by EmilyBjoerk** [comment]
In general lsml shows you the effective/true values that you will have
in-game for all stats and as such it is currently the only software that
gives you accurate information.

**Comment by albert0909** [comment]
> The cycle times for clan ac weapons include the time between each of the clan ac rounds in one shot. For ultra ac weapons the cycle time is the average cycle time taking double fire, jam chance and jam time into account.

I too was wonder why lsml's numbers were different from smurfy. The above info needs to be included inside LSML's UI.

1) Cycle Time
Personally at least, it was not obvious that mousing over the column header would produce helpful tooltips. 
Could the tooltip convey the above info as well? Perhaps something like "The amount of time between consecutive shots. Takes into account burn time for lasers and multiple pellet shooting for Clan Autocannons"

2) UAC Stats
Again sorry to say, its not obvious that the UAC stats take into account these additional factors. Perhaps a sidenote could be added to make it obvious and clear that LSML assumes the player intends to double-tap their UACs AND takes jam chance and unjam time into account already.
