### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by WarWolfen** [EmilyBjoerk/lsml#500]
Hi!

Not sure if this is a duplicate, but I'd love to see a list of my modules and to what Mech they are attached to (red out of the game to make it accurate and effortless).

Would that be usefull to anyone else as well?

**Comment by EmilyBjoerk** [comment]
Useful? Absolutely!

Unfortunately to the best of my knowledge this data is only available server-side so it's impossible for me to do this. PGI did promise an API for this kind of stuff a long time ago, but it seems to be vaporware.

**Comment by WarWolfen** [comment]
I have been waiting for this API for other things as well. I wanted to read the results of specific matches for a planetary league... Well...

Ok, nevermind!

**Comment by EmilyBjoerk** [comment]
Thank you for your input though, if you have any other ideas or bug reports. Please don't hesitate to post here. I'm closing this issue.
