### ISSUE TITLE
Clicking a highlighted item in the navigator list triggers an exception

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#513]
Clicking an item in the {Loadouts, Dropship, Chassis, ...} list, and then clicking the same item again leads to the item being de-selected and exception being triggered.

**Comment by VioletGiraffe** [comment]
P. S. Thanks for the awesome program!

**Comment by EmilyBjoerk** [comment]
I'll fix it for the next beta version.

**Comment by VioletGiraffe** [comment]
Thanks for the fix!

P. S. Hey, did you know you can close issues automatically via commit message? https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by EmilyBjoerk** [comment]
Yeah I noticed that on the commit prior to this, thanks.
