### ISSUE TITLE
Clan targeting computers beam range bonus is double of what it should be.

### ISSUE THREAD

**Issue by shalexander** [EmilyBjoerk/lsml#514]
Hello,

The TC beam range bonus is double of what it should be.

For example:
TC1 adds 8% instead of 4%.
....
TC7 adds 20% instead of 10%.

**Comment by shalexander** [comment]
Excellent tool, good work!

**Comment by EmilyBjoerk** [comment]
Thank you for taking the time to report the bug. In the future, could I ask that you also specify what version of LSML you are using?

This bug has already been fixed by #505, the fix will be in the next beta version of 2.0. As 2.0 is so close now, I'm no longer back-porting fixes to 1.7.
