### ISSUE TITLE
New 'Mech Chassis are Not Sorted

### ISSUE THREAD

**Issue by crazy6432** [EmilyBjoerk/lsml#522]
This is in the 2.0 beta version. When selecting a 'Mech from either the Chassis button on the left side, or the New 'Mech button on the top, the chassis list is not sorted at all. The Chassis button on the left lets me click on the column headers to sort, but the popup when clicking New 'Mech at the top does not let me sort the chassis at all.

**Comment by EmilyBjoerk** [comment]
Thank you for reporting. I'll get it fixed for beta 4.
