### ISSUE TITLE
Spinboxes on the "Create a new mech" dialog cannot be edited from keyboard

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#527]
Don't know if it's by design or a limitation of this control or whatnot, but it's definitely not very convenient that I can't enter values like mass, number of hardpoints etc. from the keyboard.

**Comment by EmilyBjoerk** [comment]
This is a JavaFx design thing. Oracle/Sun designed the text input (and
spinners) such that loss of focus cancels the text input (very strange if
you ask me). If you hit enter after typing the number in it'll work... The
same thing happens with all other text input and spinner fields.

I'll see if I can make some kind of fix for this behaviour.

**Comment by VioletGiraffe** [comment]
Thanks for the detailed explanation, but I literally can't input anything at all. No matter if I select the existing number or just put the cursor there and start typing numbers, the keyboard has no effect whatsoever. There's no text cursor, either. I'm not familiar with JavaFx controls, but if it was a standard Windows control I would say it's made non-editable.

**Comment by EmilyBjoerk** [comment]
Apparently it WAS non-editable... I must have missed that. But the focus thing I mentioned also exists, will still see what I can do about that.

**Comment by VioletGiraffe** [comment]
That'd be nice, but if one is using the numpad, hitting Enter after typing numbers is not a big setback.
I find typing much more convenient than clicking the little arrows up or down many times in a row. Thanks for figuring it out!
