### ISSUE TITLE
QoL: White Text on Light Grey Background

### ISSUE THREAD

**Issue by crazy6432** [EmilyBjoerk/lsml#530]
This is for the Beta 4 version. Some areas, such as the column choice popout on the Chassis view, have white text on a light grey background. This is difficult to read. I would suggest changing the text to black.

**Comment by EmilyBjoerk** [comment]
If you could please compose a list of the locations where the font is
illegible (possibly with screenshots) I can go through and fix them all in
one swoop.

Thank you for taking the time to report issues, it really helps me.

2016-04-13 18:33 GMT+02:00 crazy6432 <notifications@github.com>:

**Comment by crazy6432** [comment]
It appears to be any pop-out, drop down, or menu. I'll edit this comment when/if I find more.

What I've found so far:
1. Column choice pop-out in the Chassis view
2. Menus on the 'Mech edit window (oddly, they change to black if I mouse over another menu, then go back to a previous one)
3. Engine size drop down when editing a 'Mech loadout

**Comment by crazy6432** [comment]
You missed the engine size drop down box.
