### ISSUE TITLE
New Heat Dissipation Quirk.

### ISSUE THREAD

**Issue by NavidA1** [EmilyBjoerk/lsml#544]
A new heat dissipation quirk has been introduced this Tuesday.

Its on the locust. kitfox, adder, etc...

It would be nice if we could have it in lsml.

Also, I have a question, When you are parsing the game data files, form where are you acquiring the quirks per each chassis?

**Comment by EmilyBjoerk** [comment]
I'll get it into 2.0. The chassis quirks are in the .MDF files for standard mechs and in the omnipods.xml files for clan 'Mechs IIRC.

I then have a quirks definition file which I got from PGI but isn't in the game install data files.
