### ISSUE TITLE
Can't Remove 1st listed Module First

### ISSUE THREAD

**Issue by crazy6432** [EmilyBjoerk/lsml#546]
I noticed this in the Preview 5 build, and it persists in the Preview 6 build.

When removing modules, you have to remove the module listed last in a section first. If you remove the 1st listed module (or 2nd for 'Mechs with 3 slots), the 2nd (and/or 3rd) listed one snaps up and becomes locked until you close and reopen the 'Mech build.

**Comment by LiSongMWO** [comment]
I am unable to reproduce this. I fill the 'Mech with all manners of modules
and I can always remove all the modules by removing the first listed
module.

Could you please post detailed click-by-click steps?

**Comment by crazy6432** [comment]
Sorry for the delay. I'm in the process of moving. If you can't recreate it, it's probably a config issue with something or other on my system. Once the dust clears I'll try and post a better step-by-step to recreate.

**Comment by EmilyBjoerk** [comment]
Ok no rush. When you get the time, could you see if updating to the latest Java fixes the problem?

**Comment by crazy6432** [comment]
Updating Java does not fix the issue on my end.

**Comment by EmilyBjoerk** [comment]
Okay I've tested some more, the only thing I can tell is that if you're too quick to double click then it wont work but if you wait half a second between the double clicks, then it works. Can you see if this is what you're seeing ?

**Comment by crazy6432** [comment]
Oh, I've always used drag-n-drop. I didn't even know double clicking was a method.

**Comment by LiSongMWO** [comment]
Ah... You see,  this is why I ask for click-by-click instructions. :) I
thought you used double click as I always do... I'll check it when I get
home.

**Comment by crazy6432** [comment]
I would've given click-by-click, but my computer's in a box until Thursday.

**Comment by EmilyBjoerk** [comment]
Okay I have replicated this, I'll get it fixed for the next preview release.
