### ISSUE TITLE
Preview 6 : Loading window cannot be moved and overwrites everything

### ISSUE THREAD

**Issue by Question2** [EmilyBjoerk/lsml#552]
When starting the program, the loading window cannot be moved and overwrites everything so that you cannot view what is under it. This includes the "cannot parse files" warning popup box which is partially hidden by the loading window every time it appears.

P.S. Is preview 6 still supposed to fail to parse the current patch?

**Comment by EmilyBjoerk** [comment]
Preview 6 correctly parses the latest patch for me. If you are experiencing a problem with the parsing, please post a separate issue.
