### ISSUE TITLE
LP Laser Cooldown Module bonus in red

### ISSUE THREAD

**Issue by Maqquan** [EmilyBjoerk/lsml#569]
Equipped LP Laser Cooldown Module 5.

Result: Bonus +12% shown in red text.
Expected: Bonus in green text.

**Comment by Kmieciu4ever** [comment]
Every cooldown module in LSML 1.9.99 RC1 **increases** cooldown instead of reducing it, therefore reducing DPS...
so much for No known bugs  :-)

**Comment by EmilyBjoerk** [comment]
No known bugs means that I did not know of any bugs at the time I made the
release. As I don't have a paid stab of testers, QA is limited to what you
guys can find in the beta/RC releases.

2016-06-20 8:47 GMT+02:00 Kmieciu4ever <notifications@github.com>:

**Comment by Kmieciu4ever** [comment]
Enough excuses! I want my money back ;-)
Just kidding, you're doing a great job.
