### ISSUE TITLE
Smurfies export / import

### ISSUE THREAD

**Issue by WarWolfen** [EmilyBjoerk/lsml#574]
Hi!
I get an error message on each start that smurfie links are not working. Is that intentional for now or is something wrong with my environment?

**Comment by WarWolfen** [comment]
![image1](https://cloud.githubusercontent.com/assets/16292643/16350040/82b4a888-3a5c-11e6-9dd5-095bb91d7a06.png)

**Comment by WarWolfen** [comment]
Is it correct to get this error message still with 2.0.0?

**Comment by EmilyBjoerk** [comment]
I will look into it.

**Comment by WarWolfen** [comment]
Now I get this one:
![image](https://cloud.githubusercontent.com/assets/16292643/17309236/30a41cfe-583e-11e6-9787-a6cfe6091998.png)

**Comment by EmilyBjoerk** [comment]
@smurfy Earlier the `https://mwo.smurfy-net.de/api/data/user/mechbay.xml` endpoint used to contain LSML links for the loadouts, I used these to import the mechbay but now I can't see them there any more? 

Is this intentional? Is there any chance of getting them back?

**Comment by smurfy** [comment]
They should be present. I changed something related lsml links months ago. but this should not have any effect.  my change was that i will create the lsml link only once and then store it in my database. this change was a performance change, because mechbay and other long lists of mechs got very slow due to the lsml link generation.

Neverless i will check it soon. (probably today or tomorrow)

**Comment by EmilyBjoerk** [comment]
Thank you,  I will hold off making any changes until I hear from you then.

**Comment by smurfy** [comment]
Please try. it should be fixed now.

**Comment by EmilyBjoerk** [comment]
@smurfy Seems OK. Thanks!

**Comment by WarWolfen** [comment]
Still not working for me with 2.0.0.2

**Comment by WarWolfen** [comment]
Oh, yeah saw the milestone. All right.

**Comment by EmilyBjoerk** [comment]
It should work in 2.0.2. It worked when I tested, which error are you
getting?

**Comment by WarWolfen** [comment]
![image](https://cloud.githubusercontent.com/assets/16292643/18255857/4982b222-73ae-11e6-8151-e7eb8e7288a8.png)

**Comment by WarWolfen** [comment]
I have made a reinstall, but use the old garage file (don't know if that makes a difference).

**Comment by EmilyBjoerk** [comment]
It works for me, HTTP 401 means access denied, please double check your api
key.

**Comment by WarWolfen** [comment]
I have recreated the API key on the website and with the new one it is working. Thanks a lot!
