### ISSUE TITLE
Sorting Mechs

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#590]
First of all: Great job on LSML 2 - it looks fabulous, so thanks a lot for giving this to the community!!!

Although the UI is quite nice already, it would be great if mech loadouts were sorted (e.g. by variant name or LSML name). This could either be an option in the settings or be done by clickable column headers (like e.g. in Windows Explorer).

Any chance to include this into an upcoming release?

**Comment by EmilyBjoerk** [comment]
I can do a simple alphabetical sort as a stop gap for the next bugfix release. If you need better sorting than that please open another issue.

**Comment by Zesaric** [comment]
A simple alphabetical sort by LSML name (not variant name!) of that loadout would absolutely do the job for me. That's also the way Mechs are sorted within MWO so that definitely would be a good fit.

**Comment by anonymous555** [comment]
Consider a sort by tonnage too.
