### ISSUE TITLE
IS / Clan filters not obvious, could use a more prominent position.

### ISSUE THREAD

**Issue by silvercheckmate** [EmilyBjoerk/lsml#594]
Somewhat related to Issue https://github.com/EmilyBjoerk/lsml/issues/591 - IS/Clan filters not working

In its current position (bottom left corner) and without any visual or colour cues, this filter is easy to miss. Its technically sitting on the "navigation" panel and is not a intuitive place someone would look for a filter toggle.

I suggest moving it to the "main content" panel, perhaps something like this? 

(excuse the poor paint job)
![imgur](http://i.imgur.com/Z30OX1V.png)

**Comment by EmilyBjoerk** [comment]
The filter is used both on chassis, weapons and graphs. That's why it is positioned where it is although I'm not very happy with it being there. Neither am I happy about duplicating the checkboxes on every page they affect...  This needs more thought.
