### ISSUE TITLE
"Weapon Systems List" table headers should have tooltips

### ISSUE THREAD

**Issue by silvercheckmate** [EmilyBjoerk/lsml#596]
Under the "Weapon Systems List", all title headers should have tooltips.

Given that LSML uses plenty of jargon, abbreviations and has obscure (but yet accurate) numbers and formulas, tooltips would be very useful here.

Of special note would be 
- (future?) statistical modelling of SRM and LBX spread and hence damage values
- inclusion of laser burn time, ballistics volley firing time and clan LRM volley firing time into damage values
- for UACs, the assumption that the user intends to double tap and statistical modelling of jam rates into damage values

A link to the Wiki would be useful as well, but actually the Wiki is currently outdated. But I do remember noting that LSML takes into account the above, I might be wrong/outdated.

Perhaps a good touchstone would be, if the values differ from ingame data or Smurfy data, there should be a tooltip highlighting it, and perhaps a Wiki link explaining the logic, math and assumptions behind it.

**Comment by EmilyBjoerk** [comment]
- [ ] Add tooltips
- [ ] Write wiki pages
- [ ] Make tool tips have links to wiki pages.

**Comment by EmilyBjoerk** [comment]
I've tried to write up a new wiki page, could you take a look and see if I forgot anything?

https://github.com/EmilyBjoerk/lsml/wiki/Weapon-Stats

**Comment by EmilyBjoerk** [comment]
I assume lack of comments means it is sufficient. Please open another issue if you feel the issue is not resolved.
