### ISSUE TITLE
Engine Rating order (currently biggest to smallest) should be a configurable option.

### ISSUE THREAD

**Issue by silvercheckmate** [EmilyBjoerk/lsml#602]
I personally prefer listing engine ratings from biggest to smallest (higher likelihood of you using the larger engines anyway), but in the spirit of ease of use, I would prefer the list to emulate how it is in-game (smallest to biggest). Perhaps giving the user the choice of display options would be best.

**Comment by Zesaric** [comment]
Very good point made here by silvercheckmate, I second that.

Basically I think if giving the choice (which of course always is the best way) is too complicated, a good guideline for **any** list is to go with the MWO in-game sort order. That's what everybody is used to, so these are the sort orders most players will be comfortable with.

**Comment by EmilyBjoerk** [comment]
This issue is superseded by #628.
