### ISSUE TITLE
Windows always move to main screen

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#606]
I have a three TFT setup with MWO being on center screen and tools and websites on the side screens. 

Since 2.x now there is the problem that all LSML windows maximise to the primary screen - regardless of where they were before clicking the maximize button.

In 1.x LSML its windows reacted normally, i.e. maximising a window on a secondary screen maximised it to that secondary screen. This behaviour should be used for 2.x also.

**Comment by EmilyBjoerk** [comment]
Can you provide step by step instructions please? On my computer lsml
maximises on the screen where the mouse pointer is.

**Comment by Zesaric** [comment]
I double-checked and found that on my right side screen it does behave normally, the problem is only on the left side screen. My screen setup is 2-1-3 with screen 1 being the primary screen with taskbar and all that. Means in terms of pixel coordinates it is as follows:

- Screen 1 is pixels 0:0 to 1680:1050
- Screen 2 is pixels -1680:0 to -1:1050
- Screen 3 is pixels 1681:0 to 3360:1050

On screen 1 and 3 the window maximises to the current screen. On screen 2 it maximises to the primary screen. I presume that is because screen 2 has "negative" coordinates.

**Comment by Zesaric** [comment]
Short update here: As a workaround I now open LSML on my right hand screen so now it maximizes correctly to that screen.

However, when opening a loadout, it still opens on the main screen, whereas it would be preferable if it opened on the same screen as LSML. Maybe that could be added in a future release.
