### ISSUE TITLE
Option for L/R sync of armor is missing

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#607]
In 1.x there was the option to sync change L/R armor values. In 2.x that option is missing (or I don't find it ;))

Suggestion for technical implementation would be to place a "lock" icon next to all armor values for which there is a Left and Right side. This would bring back the familiar option while also improving on it - because the places to change the armor value and to lock the L/R sync are just a few pixels apart.

**Comment by EmilyBjoerk** [comment]
Duplicate of #524. I like the idea with the lock icons, I'll keep that in mind. Closing this as duplicate.
