### ISSUE TITLE
Sort module categories identical to MWO

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#609]
I use LSML to re-build every loadout I have in game to be able to analyse the resulting XML when searching for modules, equipment etc.

This is why I often have both the MWO and the LSML loadout screen open side by side to make sure it matches in every detail. When doing so, it is extremely helpful if the sort order of slots is identical in MWO and LSML.

For modules that currently is not the case as the order in MWO is Mech/Weapon/Hybrid/Consumable while in LSML its Consumable/Mech/Weapon/Hybrid.

The suggestion would be to change the order in LSLM to match the one in MWO. If implemented, the new order should be applied not only to the slots themselves but also to the categories in the item picker.

**Comment by EmilyBjoerk** [comment]
This issue is superseded by #628.
