### ISSUE TITLE
Verification of UAC DPS

### ISSUE THREAD

**Issue by EmilyBjoerk** [EmilyBjoerk/lsml#611]
I would like to have help from some volunteers to test the DPS values of UAC type weapons (all of them). 

Suggested testing procedure:
1. Equip a 'Mech with 1 UAC of the type to be tested, fill with ammo.
2. Use a screen recording software such as Shadow Play (nvidia) or Open Broadcast System to record the test. 
3. Drop into a private lobby (testing grounds has historically been buggy). 
4. Use a macro or manually spam the fire button until you run out of ammo.
5. Record the total time it took to deplete the ammo and number of jams and successful double fires.
6. Also record quirks, modules and whether or not quick fire was used.
7. Post here. 
8. Repeat the test a few times posting for each successful run.

**Comment by Taxxian** [comment]
I do not know what you want to achieve here, but I have written a simmulator to get exact DPS values for all those weapons. If that would help you please contact me.

**Comment by EmilyBjoerk** [comment]
@Taxxian LSML Already does the simulation and the results are included in the DPS values for all UACs. The purpose of this issue is to validate the simulation results that LSML produces.

**Comment by Taxxian** [comment]
Ok in that case I am of no help :-)

PS: What duration do you use for the different Clan Weapons?
CUac5: 11ms Cuac10: 22ms Cuac20: 33ms ?
For Clan LRMS I have .25 .5 .75 and 1s...
I could not find offical numbers for that, are you using the same and how did you figure them out?

**Comment by EmilyBjoerk** [comment]
Sure you can be of some help, drop into a private lobby with a friend and do the measurements as suggested above. :) 

Duration, I don't remember off the top of my head. You can look in the `lsml.model.datacache` package to see how I read in data and in  `lsml.model.item` for how I compute using the data read in.

**Comment by VioletGiraffe** [comment]
I've just read somewhere that mech efficiency is not taken into account while running Testing Grounds. That could explain the buggy behavior you've mentioned, and if true, that makes Testing Grounds a reliable source of data - just re-calculate your measurements to account for efficiency.

**Comment by LiSongMWO** [comment]
After reworking the code and adding additional tests. I'm fairly sure this is correct.
