### ISSUE TITLE
Include variant name in Loadout window

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#612]
In noticed that while the loadout window does display the LSML name - surprisingly it does not display the name of the Mech variant!

As I believe many people do not include the variant name in the loadout name (e.g. I use names that indicate the purpose and exact weapon loadout), it would be helpful to display the **variant name** in the Loadout window.

The best position for this would be the center of the title bar, i.e. between the "Weapon Lab" button and the loadout name. A large and very contrasting font would be ideal as the Mech variant name probably is one of the most important details to see in a loadout window.

**Comment by Zesaric** [comment]
First of all, thanks for your hard work on releasing 2.0.1 with the inclusion numerous requests! :)

Just out of curiosity a question regarding this issue: What was the rationale of putting the variant name in the loadout window where it is now in 2.0.1? I don't want to complain but I think the current position has two disadvantages:

1) If a Mech variant has a very long name, this position might run out of space.
2) At the current position, the variant name does not catch the eye but rather "disguises" itself between all the numbers. This is a downside for a piece of info as essential as the variant name.

This is why I still think putting the variant name in the title bar right above the Head slot (and in a font which is at least as big as the one for the LSML name of the loadout) would be a better choice.

Not really a big issue but a notable enhancement in my opinion.

**Comment by EmilyBjoerk** [comment]
The title bar is already quite cluttered and putting the chassis variant
there would also clash with the warning and error messages displayed. I was
also worried about it making the title bar too long as lsml has to work
with screens as small as 1024x768 when the name of the loadout is a bit
longer.

The current location was the only one I could find. I find that most people
know what chassis they are working on as they knew that when opening it, as
such it is not a necessarily high priority piece of information.

**Comment by Zesaric** [comment]
Thanks for your explanation, I can follow that rationale. Also I must admit I forgot about resolutions below 1680x1050, so I understand your decision not to put it into the title bar.

One question though: Is the variant name format somewhere in the CSS?

As you know, I wanted to give it a try creating a more visible style, so I while doing this I could as well try to improve the visibility of the variant name. Which personally I feel is a very important piece of information: E.g. I frequently have several loadouts opened - and if I have only one loadout opened, my mind seems to be too old to remember which variant it was that I opened a second ago... ;-)

**Comment by EmilyBjoerk** [comment]
I did not put a CSS style on the variant name when I added it. 

However you can open up the "LoadoutWindow.fxml" file (it's just a plain XML document) and add a new style class to it by either adding an attribute to the node: `styleClass="myclass"` or by adding a child node as such: ` <styleClass><String fx:value="myfirstclass" /><String fx:value="mysecondclass" /></styleClass>`.

As a side note you can also customise pretty much the entire UI by moving nodes around in the FXML documents and LSML will still function. However there are some nodes which are expected to be in certain relations with their parents. I don't remember all of them at hand, you'll notice when you run into one ;)

If you feel up to improving the looks and UI you're more than welcome to check out the source code, edit the relevant files and make a pull request. I can get you setup with the tools I use if you want to.

**Comment by EmilyBjoerk** [comment]
Also I have to apologise, the CSS structure is a bit of a mess. I'm intending to go through and clean it up and restructure it when I get the time.

**Comment by Zesaric** [comment]
Thanks for the pointer regarding the LoadoutWindow.fxml, I'll have a look into it.

As for your side note: I enjoy improving the looks and UI of a software and I gladly can offer you to help in that department if you like.

I must point out though that while I am comfortable with XML and CSS, I have zero knowledge of Java or other development languages.

So if you're using specific tools to work on the UI aspects of LSML, I'd appreciate your help in setting them up. Right now I only use Notepad++ which up to now has done the job for me whenever I was working with XML/HTML/CSS.

**Comment by EmilyBjoerk** [comment]
I use eclipse, get the one for JavaSE development. You'll also need git to
access the source, you can use either git for windows or githubs client,
whichever you prefer. For editing the fxml documents I use scenebuilder by
gluonhq. I'm out and about right now but I can help you later over TS if
you would like to.

**Comment by Zesaric** [comment]
Thanks for pointing out the tools. I think that I will be able to come up with an improved color theme which also is my first priority. The piece that is missing for me here is to find a good method of playing around with the colors and seeing the effect right away. Currently, editing a CSS code and repacking the JAR to start it is not a very efficient process. Maybe you have an idea what better process I could use to play around with the theme colors?

As for improving the UI itself, I have downloaded scenebuilder and had a quick look into it. It looks intuitive but I must say I have concerns that I might crash functionality of the UI, because I am not fully aware of all the interaction between the elements. So if we could talk about all this via TS, it might be helpful.

On a side note, I'm going on vacation with my family in a few days and will only be back later this month. I won't find the time to properly look into the tools and resources before that, so we might as well have a chat via TS when I'm back. In fact, you could let me know where on TS to catch you and then we could arrange a chat later this month. What do you think?

**Comment by EmilyBjoerk** [comment]
By using eclipse which is the IDE (integrated development environment) that
I use and checking out the source code from github you can launch lsml
directly from the source using eclipse thus you will not need to fiddle
around with the jar.

Also in scenebuilder you can add the relevant css files to get a live
preview of the changes as you go. Although some things are done from code
and are not visible in scenebuilder...

I'm usually on Comstar NA. I too will be gone the week after next week. We
could try to find a date and time, I'm CET timezone.

**Comment by Zesaric** [comment]
Thanks, that sounds like the process I was looking for - having a tool that allows a color theme preview while trying different alternatives.

Anyway, as we're both away during the following weeks, I suggest that I'll contact you when I'm back (after September 20). We shouldn't have any difficulty in finding a date and time then as I'm in CET timezone too! :-)
