### ISSUE TITLE
LSML not working with Java 8u102

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#613]
After updating Java to 8u102, LSML fails to start saying something like "Java 8u77 or higher is required". 

This is why I went back to 8u77, after which LSML starts as normal.

So it looks like this is a problem specific to 8u102.

**Comment by EmilyBjoerk** [comment]
This is a 🐛 in a tool that LSML uses. I've been in contact with the maker
of the tool and a patch is due soon. Meanwhile you can work around this 🐛
by starting lsml directly from the lsml.jar file in your installation
directory.

I have out notices in forums and all social media where lsml is present.

**Comment by Zesaric** [comment]
Thanks for your swift response and your recommended workaround! *thumbs up*

Should I have a future need to install Java in its latest version, I'll use your workaround, but until then I'm also perfectly ok with having Java 8u77 and starting LSML as usual! :-)

**Comment by EmilyBjoerk** [comment]
Tools upgraded, issue will be automatically fixed next release.

**Comment by Zesaric** [comment]
Sorry to report this, but LSML still says _"This application requires a Java Runtime Environment 1.8.0_77"_ at startup.

Not a big deal as I now switched to the workaround of starting the JAR file directly, I just wanted to report it for information. My config is Win 10 x64 with Java 1.8.0_103-b13.

**Comment by EmilyBjoerk** [comment]
Dadgum... I'll look into it tomorrow then...

**Comment by Zesaric** [comment]
Thanks for the fix! :) I can confirm that 2.0.2 now does start properly on my machine with 1.8.0_103.
