### ISSUE TITLE
Clan Omnipod Quirks not applying to Projectile Speed in Tooltip

### ISSUE THREAD

**Issue by mat3049** [EmilyBjoerk/lsml#615]
The projectile speeds in the tool-tip previews for weapons in the equipment sidebar do not appear to include the quirks from individual Omnipods on Clan Omnimechs.

This applies for both energy (C-ER PPC) and ballistic weaponry.

NVA-C LA w/ Gauss:
![c-gauss velocity](https://cloud.githubusercontent.com/assets/9911831/17455801/b103d3c2-5b80-11e6-9fd1-5144f5bb389d.png)

SMN-PRIME RA w/ ERPPC:
![c-er ppc velocity](https://cloud.githubusercontent.com/assets/9911831/17455802/b109c30e-5b80-11e6-9209-85e2a40fa015.png)

However, it does appear that the projectile speed increase from Targeting Computers is being applied correctly.

SMN-PRIME RA w/ ERPPC + TC1:
![c-er ppc velocity w tc1](https://cloud.githubusercontent.com/assets/9911831/17455803/b10a4ae0-5b80-11e6-91a4-3c5375ce83fd.png)

**Comment by EmilyBjoerk** [comment]
I'm currently on holidays I will look into this when I get home at the end of August.
