### ISSUE TITLE
HBK-4J - Incorrect Right Torso Armour Amount

### ISSUE THREAD

**Issue by Bilagaana** [EmilyBjoerk/lsml#616]
LSML version: 2.0.0

http://t.li-soft.org/?l=rgAVHywEMBI7BSwEMB%2Fne6%2FupzrMtttt

Steps to reproduce:
1. open lsml
2. View the HBK-4J

Actual result:
Right torso has 48 max armour

Expected result:
Right torso has 60 max armour
![image](https://cloud.githubusercontent.com/assets/21003681/17641545/8fa49636-60d9-11e6-8d02-7a66bb5923f0.png)

**Comment by EmilyBjoerk** [comment]
I'm currently in holidays and unable to test this myself...

I think that in a recent patch pgi changed the in game mechlab to include
armour from quirks in the displayed amount in the spinner. You can test
whether this is the case by attempting to set the front armor to zero in
your screenshot. Or by attempting to set rear armour to 60 neither of these
should be possible if my hunch is correct.

Lsml shows the base armour amount with any bonus from quirks to the right
of the armour amount.

Could you test the above and report back please?

**Comment by Bilagaana** [comment]
That guess is actually correct.

See the screenshots below:
![image](https://cloud.githubusercontent.com/assets/21003681/17645101/33c7db9e-6150-11e6-9ac3-256468be43fe.png)

I can't get the front armour down to 0, stays at 12, giving me 48 to play around with.
