### ISSUE TITLE
Please bring back Save Garage option from LSML 1.x

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#617]
LSML 1.x had the option to save the garage without closing LSML. This was very helpful as it allowed users to edit a loadout, save the garage and then query the saved Garage XML without having to close LSML.

This is why it would be great to see the same feature in LSML 2.x again.

**Comment by EmilyBjoerk** [comment]
Can you give me a user story so that I can better understand your use case? So that I don't make a stupid  adding the functionality somewhere silly :3

**Comment by Zesaric** [comment]
Sure, as discussed I query the garage XML from LSML with Excel to get an overview where all my modules, engines etc. are equipped. In this setup, it's quite frequent that I modify a loadout in LSML and need to see the result in Excel right away.

This is why it would be helpful to update the garage XML without having to close LSML. Which is exactly what the Save Garage option in LSML 1.x did! :-)

**Comment by EmilyBjoerk** [comment]
Save garage button has been added to settings page.
