### ISSUE TITLE
User option to define UI colors

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#620]
As color always is a matter of taste it could be a good idea to add an option in the settings to select a color value for every UI element like

Empty slots
Dynamic Armor/Structure slots
Equipment slots
Background
Scrollbars
etc.

I am fully aware this requires much more work initially than to simply change the color of one element, but it could resolve any coloring issues in advance as every user can just use the colors they like best.

**Comment by EmilyBjoerk** [comment]
I'm not going to add settings for each UI element. That is too much work. 

It is possible to create your own colour themes by editing the .css files in the lsml.jar file. In the future I will add an option to load external .css files so that theming can be realized easier but that's in the future.

**Comment by Zesaric** [comment]
Wow, thanks for the idea with the CSS, that's what I was looking for!!! :-)
I will definitely try this method to create an alternative color scheme which I hope improves readability.

BTW, I fully understand that you have discarded the idea of adding settings for all UI options. I cannot fully judge how much work implementing a give idea might be, so I'm just submitting them really as **ideas** rather than expectations.

One final note: After unpacking the JAR to find the CSS, seeing all these files puts me even more in awe about how much work you've put into LSML. That's just wow and so awesome that you're doing all this for the community, so thanks again!!! :)

**Comment by EmilyBjoerk** [comment]
Thank you. I don't think many people realise the amount of work that goes into making software. For example LSML is the product of thousands of hours of work by a professional software engineer, released for free to the public.

If you like the software, please consider supporting the future development of LSML through the Patreon campaign here: https://www.patreon.com/LSML.
