### ISSUE TITLE
Import from Smurfies

### ISSUE THREAD

**Issue by WarWolfen** [EmilyBjoerk/lsml#623]
Found another issue... if I take over Mechs from Smurfies into a generated sufolder, the variant is empty.

I have created subfolders in my garage:
/ 60-75t Heavy / 60t - MDD - Maddog

If I import a variant from smurfys into that folder, the variant ends up to be weaponsless in LSML.

**Comment by WarWolfen** [comment]
Happened just once. I imported the Mech into the Main folder and it worked. Now it also works everywhere. No glue.
:(

**Comment by EmilyBjoerk** [comment]
If you find steps to reproduce this please re-open the issue. I'm closing this as it is working for me.
