### ISSUE TITLE
Weapons lab alpha heat bug

### ISSUE THREAD

**Issue by NavidA1** [EmilyBjoerk/lsml#626]
Hi

I think there is a bug in weapons lab where removing weapons from the mech affects alpha heat of a selected group that is not including that weapon.

example:
Summoner: 2xERPCs + 1 ERML and 18 double heat sinks gives you about 33% alpha heat with both ppcs selected in a group in weapons lab.
However, if you remove the ERML, that percentage jumps to 40% (becomes hotter?). Its now 2 ERPPCs and 18 doubles, with the same pods, but now the alpha heat is higher without that med laser which should not be the case. The alpha heat from ppcs should have stayed the same.

Thank you so much.

**Comment by EmilyBjoerk** [comment]
I'm unable to reproduce this in 2.0.1.

Please provide click by click instructions and a link to a build where you can reproduce the issue and which version of LSML you are using.

**Comment by NavidA1** [comment]
I'm using 2.0.2
This is the example build (all efficiencies unlocked):
http://mwo.smurfy-net.de/mechlab#i=187&l=993939e2443b68f92eed70121b2b9e3b7d9bad00

If you go to the weapons lab, and select the two PPCs as group 1, you'll see that the stats for that group shows 33% for alpha heat

Now if you remove the single ER M laser and check the stats again, it shows 39%.

Group 1 is only PPCs and the number of heat sinks did not change, so removing a medium laser should not change this number.
