### ISSUE TITLE
There exists no original omnipod for SMN/HBR F at Head

### ISSUE THREAD

**Issue by XikuKiju** [EmilyBjoerk/lsml#630]
When starting up Li Song I immediately receive [these](http://i.imgur.com/Gnw8fNM.png) error messages. The search function stops working completely. I am using 2.0.2.

**Comment by EmilyBjoerk** [comment]
Thanks for the report!

This is a duplicate of: https://github.com/EmilyBjoerk/lsml/issues/627 which is on the way out in a few minutes. Sit tight :)
