### ISSUE TITLE
"Set of 8" quirks not being added

### ISSUE THREAD

**Issue by IK4MS** [EmilyBjoerk/lsml#639]
As seen [here](https://static.mwomercs.com/downloads/Clan%20Quirks_11-15-2016.pdf), new quirks apply to mechs having 8 omnipods from the same chassis. This doesn't show up within Li Song Mechlab.

**Comment by EmilyBjoerk** [comment]
Until now the set bonus only included xp which was kind of useless for lsml
so I'm currently not parsing the bonuses. I'll get this fixed for the next
release in a few weeks or so.
