### ISSUE TITLE
Grasshopper 5H(S) tonnage oddities

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#646]
Here's the loadout I'm playing with. It's also saved in the garage that I attached.

![Buggy loadout screenshot](http://i.imgur.com/0fhJKMo.png)

Problem: either I'm blind, or there's something odd with the tonnage number. Here's the same loadout in-game. Note that it has _more_ armor, and it's still _lighter_!

![In-game screenshot of the same loadout](http://i.imgur.com/w6lFqTB.png)

I hope you will be able to debug this just by opening this loadout from my garage.
[LSML.zip](https://github.com/EmilyBjoerk/lsml/files/690431/LSML.zip)

**Comment by LiSongMWO** [comment]
What version?

**Comment by LiSongMWO** [comment]
Lsml is functioning correctly. You cannot increase the armor because you
are already at max. It's a difference of how the armour is displayed when
armour quirks are present.

See issue #616.

**Comment by LiSongMWO** [comment]
Also notice how the armour amounts on your mech in the in game mechlab
don't add up to the armour sum of the armour on the components...

**Comment by VioletGiraffe** [comment]
LSML version 2.0.4.
There is 376 frontal armor and 404 total armor (front and back) on this build. The game shows 362. LSML shows the right amount.
But what's with tonnage? I have used LSML many-many times and had not had such a discrepancy ever before.

**Comment by LiSongMWO** [comment]
The tonnage is correct, the armour amount on the in game mechlab has the
quirk bonus added in so your screenshots do not have the same amount of
actual armour sans quirks. While lsml shows the base amount and the bonus
is shown as +12 on the side. This is explained in #616.

You can tell this by the fact that you cannot reduce the arms to zero
armour in the in game mechlab. The reason the tonnage is not the same is
that your mech in game has less actual armour as the quirk bonus is not
counted towards the base armour, hence it is also not shown.

**Comment by VioletGiraffe** [comment]
Now I understand, thanks! A but confusing, possibly not only for me. Not that I'm suggesting anything :)

**Comment by EmilyBjoerk** [comment]
Because mwo's internal mechlab is in itself inconsistent (armour doesn't sum up to the correct total) no matter what I do LSML will either be inconsistent with itself or in game mechlab. I'm at a loss to what to do. 

I will close this for now but I will try to think of a solution.

**Comment by VioletGiraffe** [comment]
Should have named that label `working as intended©` ;)

In my personal humble opinion, players (i. e. I) look at the individual component armor amounts, not at the total counter (I didn't even know where it is until today).

**Comment by EmilyBjoerk** [comment]
Personally I look at the total amount to see that I have the intended amount and may adjust the distribution on the fly.

**Comment by VioletGiraffe** [comment]
The how about matching apples to apples? Make per-component amounts match the game as well as the total amount, and to avoid confusion add a second number, e. g. `365 (390 with quirks) / 420 (450 with quirks)`.

**Comment by LiSongMWO** [comment]
https://github.com/lisongmechlab/lsml/wiki/HowToContribute hot off the press. 

I'll think about it but that would make the text too long.

**Comment by VioletGiraffe** [comment]
That was quick! (yuck, Eclipse... Have you tried IntelliJ IDEA?)
As for the armor - you're right, not much free space to about. You could put the second display option in a tooltip/hint, but then people would not realize there are two ways of displaying the numbers. I don't have a good solution.

**Comment by EmilyBjoerk** [comment]
Realise that LSML is now almost 4 years old. IntelliJ wasn't much of a thing when I started. And yes I've tried it but it missed some plugins I wanted and some other things. You can use IntelliJ as long as you use the same formatting settings and compiler settings.
