### ISSUE TITLE
WIki: "How to contribute" page questions / suggestions

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#649]
1. Is there a reason why the page title has no spaces?
2. Could be worth nothing that you're supposed to get Eclipse Java package and not the Java EE package, because the latter lacks Gradle plugin out of the box.
3. It's unclear how to import/apply `.settings/org.eclipse.jdt.core.prefs`, Googling turned up nothing useful.

**Comment by EmilyBjoerk** [comment]
1. Because I suck at wiki. Fixed.
2. Uh yeah I keep forgetting that there are a gazillion packages. Fixed.
3. In eclipse it should be automatic if you imported the project. If eclipse overwrote it, restore it from the repository after importing the project. In other IDEs, I have no clue to be honest manually reading the settings and finding the equivalent?

**Comment by EmilyBjoerk** [comment]
And 3 is fixed to.

**Comment by VioletGiraffe** [comment]
Just a quick question about item 3 then, to avoid creating new unnecessary issues: is normal to have 3530 Java problems upon importing the project from a freshly cloned repo? It builds and runs, but reports a lot of nonsense. I thought maybe your prefs were supposed to address that.

**Comment by EmilyBjoerk** [comment]
Oh crap yeah, I forgot about that. You need to install the "e(fx)clipse" plugin which sets Eclipse up for JavaFX, which gets rid of the bazillion problems. I'll fix that in the wiki.

**Comment by VioletGiraffe** [comment]
That leaves me with 41 warning-level problems (yellow, not red).

**Comment by EmilyBjoerk** [comment]
Yeah sounds about right, some deprecated stuff that I haven't had time to
fix yet is leaving some warnings to remind me to fix it.

2017-01-09 20:08 GMT+01:00 Violet Giraffe <notifications@github.com>:

**Comment by VioletGiraffe** [comment]
Thanks, case closed then :)

**Comment by EmilyBjoerk** [comment]
Remember to tag any issue you wish to work on to avoid double work.  :)

**Comment by VioletGiraffe** [comment]
Oh, good one! That advice might be worth spelling out on the Wiki, too.
I'm just stumbling around for now, seeing what's where, and whether or not I'll manage to even find the place where my stuff might belong :)
