### ISSUE TITLE
Can the creation of the desktop shortcut be made optional in the installer?

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#650]
No big deal, but it's a bit annoying having to delete that shortcut after each update.
Also, the new icon is... unexpected.

**Comment by EmilyBjoerk** [comment]
Right now, deleting the shortcut is two clicks (right-click, delete). Adding an options page to the installer adds another two clicks if you want to remove the shortcut (uncheck the box, then next) and one click for every one else (they have to click "next" one extra time).

This is a net increase in the average number of clicks to install LSML and no reduction in the minimal number of clicks for any one. Hence I don't think it is a good idea. So I'm not sure it actually saves you any effort to have an option to not install it.

I have not changed the icon that I know of.... screenshot?

**Comment by VioletGiraffe** [comment]
I thought you might not have changed it, but wasn't sure so I couldn't call it a bug straight away:)

http://i.imgur.com/IPNPgQr.jpg?1

As for the installer option - I don't agree, but understand.
Do you use any Apple tech? They seem to employ the same philosophy :)

**Comment by EmilyBjoerk** [comment]
The icon thing is a windows bug (my bf has it too).

https://www.google.se/search?q=windows+wrong+icon&oq=windows+wrong+icon+&aqs=chrome..69i57.4287j0j4&sourceid=chrome&ie=UTF-8#q=desktop+program+wrong+icon

I don't use Apple (some one has already eaten from it!). However in general, adding customisation options that do not improve a particular task in terms of effort only serve to add more things that could go wrong to your program. It adds complexity (bugs) and/or cost (time) for me when there is an easy solution without any cost (just delete the shortcut).

**Comment by VioletGiraffe** [comment]
Odd. I sometimes (rarely) get blank white icons, but never the one on the screenshot. But yes, you're right, I ran repair on LSML and now I have the right icon.

Genius remark about Apple, I shall mock some of my friends with it :)
