### ISSUE TITLE
Adding/Removing engine from mech breaks program window

### ISSUE THREAD

**Issue by Rydiak** [EmilyBjoerk/lsml#654]
**LSML version:** 2.0.5
**Screen resolution:** 1920x1080
**Java version:** 8 update 111

**Steps to reproduce issue:**
1. Open LSML
2. Open a build from your garage
3. Add or remove an engine from the mech (XL or STD, doesn't matter)
4. Horizontal window scaling will be broken, requiring you to close the mech build and reopen it in order to do something that is on the left or right sides of the window (no scroll bar is placed at the bottom)

**Actual result:**
Window scaling became messed up when adding/removing an engine

**Expected result:**
Engine was added/removed without breaking the program window

**Comment by EmilyBjoerk** [comment]
I do not experience a problem when following your steps. Can you give a screenshot and more detailed explanation please?

**Comment by Rydiak** [comment]
Open Li-Song
![ls1](https://cloud.githubusercontent.com/assets/15963532/21999429/b1be6106-dbff-11e6-98f6-8311d41d6be1.png)

Select a mech (works for all currently in my garage.  I am going to test next with an entirely new mech)
![ls2](https://cloud.githubusercontent.com/assets/15963532/21999445/c0678048-dbff-11e6-855b-ef02bfb87057.png)

Open mech with an engine equipped
![ls3](https://cloud.githubusercontent.com/assets/15963532/21999451/cb80388a-dbff-11e6-835f-09ee949200e6.png)

Remove engine by double-clicking it or picking it up, breaking horizontal window scaling
![ls4](https://cloud.githubusercontent.com/assets/15963532/21999460/d445613e-dbff-11e6-9037-d1ed9ba46e9e.png)

-Or-

Open mech WITHOUT an engine equipped
![ls5](https://cloud.githubusercontent.com/assets/15963532/21999492/0acb3f3a-dc00-11e6-8ae6-c8208f218cea.png)

Add an engine by double-clicking it from the engine list or dragging it, again breaking horizontal window scaling
![ls6](https://cloud.githubusercontent.com/assets/15963532/21999511/1d6aa28e-dc00-11e6-97be-de03b245bfea.png)

**Comment by Rydiak** [comment]
Does NOT happen on a new mech.  Only my current mechs (which I have had in "garage" since several versions ago) exhibit this issue.

**Comment by Rydiak** [comment]
I think I found the culprit.  If the mech has a center-torso mounted item (weapon, AMS, etc) this bug will occur.  I have been able to reproduce it 100% of the time on any mech with a center-torso item slot, not only by adding and removing engines but also by adding and removing weapons and AMS.

**Comment by Rydiak** [comment]
Using the lower-right resize handle, if you pull the window out larger the issue resolves itself.  However, if you pull the window in smaller the issue magnifies.

![ls7](https://cloud.githubusercontent.com/assets/15963532/22000192/78e0ccb2-dc03-11e6-85d8-ae6f67c2084b.png)

![ls8](https://cloud.githubusercontent.com/assets/15963532/22000194/7ba6ffc0-dc03-11e6-966b-8416118e1cc3.png)

![ls9](https://cloud.githubusercontent.com/assets/15963532/22000197/7e700d46-dc03-11e6-825b-1697534fad99.png)

**Comment by EmilyBjoerk** [comment]
Nice! Thank you for the exhaustive testing, I've been able to reproduce this my resizing the window. There is definitely something going on here. I think this might be related to #656. 

Also there is something going on with your fonts. Compare to what it looks like on my computer:
![image](https://cloud.githubusercontent.com/assets/5306929/22030958/83ac6b7e-dcdf-11e6-86f2-c848829a8f07.png)

Your fonts are bold and slightly bigger than mine which I think may cause it to trigger easier for you. So that's probably another issue I need to look into. What OS are you on? Do you have a font called "Rajdhani" installed? It shouldn't affect LSML as the font is bundled in LSML but if you also have it installed there might be some interference. If you do have the font installed, would you mind uninstalling it temporarily to see if it affects how fonts are displayed in LSML?

**Comment by EmilyBjoerk** [comment]
I've been looking into this issue now and I'm starting to suspect a JavaFX bug as the behaviour is clearly inconsistent. Here's what I do:

1) Open empty mech.
2) Add anything to any component. 
3) Shrink window, the window is clipped as the contents of the component doesn't resize. 
4) Grow window back to normal size, remove the added item.
5) Shrink window, the window is now not clipped as the contents of the component resize properly. 
6) Add item to any component while the component is shrunk, The component stays at its intended size even after resizing the window. 

I'll look into this some more later but I'm not sure if I'm going to be able to fix this on my end.

**Comment by Rydiak** [comment]
Windows 10 64-bit, and I do *NOT* have the Rajdhani font installed, which is odd if you say it comes packaged with LSML.  Additionally, I am using the 64-bit version of LSML.

![rajdhani](https://cloud.githubusercontent.com/assets/15963532/22053339/95927190-dd15-11e6-9969-f361a2b64106.png)

**Comment by Kmieciu4ever** [comment]
I can confirm that manually installing Rajdhani font fixes the resize issues.

**Comment by EmilyBjoerk** [comment]
@Rydiak  and @Kmieciu4ever  did manually installing the font in windows change the appearance of the font in LSML?

**Comment by Kmieciu4ever** [comment]
Yes it did. Maybe try uninstalling the font on your PC and see the difference for yourself.

**Comment by Rydiak** [comment]
Yes, the font in LSML was visibly different after installing Rajdhani.
