### ISSUE TITLE
Offensive stats don't fit the screen even on decently large monitors

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#657]
It's annoying that I can never read the range of my weapons.

![](http://i.imgur.com/ffTZFDl.png)

Suggestion: lay out this data in one column instead of two. Then at least all the text will fit and vertical scroll will work. I can collapse the side bar parts that I don't need, and everything I do need will still fit the screen.

This is a 1920x1080 monitor, no scaling (i. e. 100%).

It also seems that the central view, the mech loadout, can be harmlessly shrinked to allow for more space to the poor side bar.

**Comment by EmilyBjoerk** [comment]
The layout could use a bit of tweaking. Also there is a font issue that was fixed in a recent commit but not in production yet (the text shouldn't be bold which should affect the default widths of stuff.
