### ISSUE TITLE
Sharing to Smurphy fails: "sun.security.validator.ValidatorException: PKIX path building failed"

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#660]
I suddenly started getting the following error when exporting to Smurphy's:

> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

![image](https://cloud.githubusercontent.com/assets/1175926/23102837/30af66da-f6b9-11e6-8ee0-1351fa0f7c67.png)

Smurphy's web site appears to be working normally.

**Comment by EmilyBjoerk** [comment]
I know, he had changed certificate provider and I need to add the provider
to the trusted key file in lsml.

I just haven't had time to work on lsml for a while.
