### ISSUE TITLE
Parse error no default omnipod for HBR-F Head

### ISSUE THREAD

**Issue by EmilyBjoerk** [EmilyBjoerk/lsml#661]
java.lang.IllegalArgumentException: There exists no original omnipod for HBR-F at Head
	at org.lisoft.lsml.model.datacache.OmniPodDB.lookupOriginal(OmniPodDB.java:149)
	at org.lisoft.lsml.model.loadout.DefaultLoadoutFactory.produceEmpty(DefaultLoadoutFactory.java:168)
	at org.lisoft.lsml.view_fx.ChassisPage.setupTableData(ChassisPage.java:282)
	at org.lisoft.lsml.view_fx.ChassisPage.setupChassisTable(ChassisPage.java:172)
	at org.lisoft.lsml.view_fx.ChassisPage.<init>(ChassisPage.java:152)
	at org.lisoft.lsml.view_fx.MainWindow.<init>(MainWindow.java:77)
	at org.lisoft.lsml.view_fx.LiSongMechLab.lambda$7(LiSongMechLab.java:496)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Tyler799** [comment]
Also getting this exact issue. Hope to see a fix soon. :)

**Comment by Zesaric** [comment]
Is there any way to start LSML despite that error? In the sense of ignoring the HBR-F but still being able to access the other Mechs in the garage?

**Comment by MichaelNuhn** [comment]
I have this error as well. I assume uploading the error text is unnecessary?

**Comment by VioletGiraffe** [comment]
I assume a workaround would be to use bundled data instead of game data. But how can I switched to bundled data when I can't launch the program to access the settings? Where are the settings actually stored?

**Comment by EmilyBjoerk** [comment]
Lsml should use the bundled or last successful parse if it fails.
Apparently there is a bug preventing it in this particular case, I'll have
to look into it. You can try to set the force bundled data option in the
config file. It is under "%appdata%\lisoft\lsml"  if I recall correctly. Be
aware though at this point the bundle may be very old and may not contain
all mechs so your garage may fail to load anyway. You could take the data
cache file from the appdata folder above and replace the data cache file in
the jar file in your lsml install directory. It's just a zip file, open it
up and look in the resources folder.

Please consider supporting the development of lsml by becoming a Patreon.
Every little bit helps in reaching the goal of being able to work on lsml a
dedicated amount of time each month.

**Comment by VioletGiraffe** [comment]
I deleted the game folder path setting from config, then chose to use bundled data, and... Still got the error and it still hangs.

**Comment by EmilyBjoerk** [comment]
Try adding `core_forceBundledData` to `true` like the others.

**Comment by VioletGiraffe** [comment]
Did as you said - no effect.
Then I pulled all the new stuff from the repo, opened the project in Eclipse, ran it, and... it still hangs just the same. Is that normal?

**Comment by EmilyBjoerk** [comment]
shouldn't hang no. And it works for me. are you sure you got all the latest changes? check the git log.

**Comment by VioletGiraffe** [comment]
Positive: I even deleted the repo and cloned it anew

![image](https://cloud.githubusercontent.com/assets/1175926/23334818/93a1d994-fbaf-11e6-9f66-a7e843b04ef1.png)

**Comment by EmilyBjoerk** [comment]
I have no idea why it would do that for you. Make sure eclipse is actually running the latest code (refresh, rebuild), if that doesn't work then I'm out of ideas unfortunately.

**Comment by VioletGiraffe** [comment]
It hangs in `fromXML()` in the line `dataCache = (DataCache) makeDataCacheXStream().fromXML(is);`.

**Comment by EmilyBjoerk** [comment]
That indicates that the XStream library is hanging when it tries to read the cache. I'm guessing the cache is either locked by some other program (any open text editors or something?) or maybe corrupt. Try removing the cache from %appdata% or restarting the computer to clear possible file locks.
