### ISSUE TITLE
Drag and drop for Equipment not working?

### ISSUE THREAD

**Issue by spardose** [EmilyBjoerk/lsml#674]
Hello there,
I am not sure if this is a bug or an error on my side, but it seems to be impossible to drag and drop Equipment on a mech, or move it around when it is installed on a mech. Are there some special settings that have to be chosen, or is that working as intended?
Regards

**LSML version:** 2.0.6
**Screen resolution:** 1920x1200
**Java version:** 8.31

**Comment by EmilyBjoerk** [comment]
I've had it happen once where drag and drop stopped working for no apparent
reason. I tried debugging it and could find no cause on my side. However
rebooting my computer fixed it, it may be a java/windows bug.

Please let me know if a reboot doesn't fix it.

2017-05-01 13:36 GMT+02:00 spardose <notifications@github.com>:

**Comment by spardose** [comment]
Hello, 
reboot did fix it, thanks for your help.
Regards

**Comment by EmilyBjoerk** [comment]
For further reference: When it happened to me, drag and drop stopped
working in Windows as well (explorer for example). I suspect it's a Windows
bug that's maybe triggered by Java in some way. But this is nothing but
idle speculation.
