### ISSUE TITLE
Not updating from game files 

### ISSUE THREAD

**Issue by boboben1** [EmilyBjoerk/lsml#676]
**LSML version:** 2.0.6
**Screen resolution:** 1920x1200
**Java version:** 8u131

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
Could not parse game data!

It is not parsing game data. I just downloaded the software and am experiencing this issue. Apparently people on the forums are also experiencing it.

**Comment by FirstDagger** [comment]
Can confirm, needs fixing ASAP

**Comment by EmilyBjoerk** [comment]
@FirstDagger If you need it fixed "ASAP" then you're welcome to contribute either by code or on the patreon page.

**Comment by EmilyBjoerk** [comment]
Was fixed as part of #679.
