### ISSUE TITLE
Parse error after Civil War patch

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#684]
**LSML version:** 2.0.7
**Screen resolution:** 1680x1050 (3x)
**Java version:** 8u112

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
As expected, the Civil War patch has changed the data structure, so LSML now throws a parse error.

**Expected result:**
LSML should have started without parse error.

**Comment by boboben1** [comment]
Yea. I can confirm.
