### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by BTGbullseye** [EmilyBjoerk/lsml#701]
**LSML version:** 2.0.6-2.0.7 both 32 and 64 bit versions
**Screen resolution:** 1600x900
**Java version:** 8u144

**Steps to reproduce issue:**
1. Open LSML

**Actual result:**
Parse Error. Image here: https://i.imgur.com/rlpFaS2.png

**Expected result:**
Parse completes successfully, and the program opens without error.

**Comment by EmilyBjoerk** [comment]
Duplicate of #684.

**Comment by sabreking** [comment]
please please release 2.0.8 i started playing the game after civil war and LOVE your software,, but its giving parse errors :( been patroling this repo for weeks now,, LOVE YOUR WORK
