### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#705]
Suddenly getting this error. I believe it worked previously and no MWO updates had been released since (although I may have forgotten some micro update a while back).

![image](https://user-images.githubusercontent.com/1175926/29243753-9b4fd54a-7faf-11e7-80c2-4a8388bdb068.png)

**Comment by fergonaut** [comment]
I can confirm. I have exact same issue. All updates installed.
