### ISSUE TITLE
Add new armour types

### ISSUE THREAD

**Issue by EmilyBjoerk** [EmilyBjoerk/lsml#713]
In [2017-07-18 patch](https://mwomercs.com/news/2017/07/1859-patch-notes-14126-18jul2017) new armour types were added:

* Light Ferro Fibrous armour
* Stealth Armour

The addition of these armour types requires refactoring of existing code that assumes that only one type of armour upgrade exists as well as updates to the UI to support multiple armour types.

**Comment by sabreking** [comment]
glad to see you are working on this again, cant wait, i wish the project was in c# then i could have definitly joined in to help,, love this software

**Comment by VioletGiraffe** [comment]
@sabreking: Java is not that different. I have no problem working with Java code, and I'm a C++ programmer; C# is much closer to Java than C++. Practically, the difficulty is understanding someone else's code, the high-level architecture of the project and things like that. The particular language is not a difficulty.

@EmilyBjoerk: Super excited to see you back as well!

**Comment by sabreking** [comment]
@VioletGiraffe  you are very right, but someone just jumping into a new language and a new code base, ill probably be a hindrance for sometime.

**Comment by EmilyBjoerk** [comment]
That's odd... I could have sworn that I replied to this but apparently I didn't.

@sabreking @VioletGiraffe Java is very similar to C++ and even more similar to C# (I came from C++ and was "professional working level" proficient in like 1-2 weeks) so please don't let that stop you. 

If you feel intimidated by the fact that it is a somewhat large code base; I always need help to add more unit tests and improve the code coverage. And that is a great way to make useful contributions, while learning the code base and Java without risking to break anything.

**Comment by EmilyBjoerk** [comment]
Was mostly fixed in commit 135f13a8e81b2f88e9f223fc7edd70efec33e53e with some trailing fixes in the following commits.
