### ISSUE TITLE
The java link given by the app takes to java 8 download.

### ISSUE THREAD

**Issue by sabreking** [EmilyBjoerk/lsml#725]
Downloading that java doesnt work.the app doesnt run. it should give this link 
http://www.oracle.com/technetwork/java/javase/downloads/jre9-downloads-3848532.html

wouldn't have been a big issue but i had to actually look harder than i should have to find JRE 9.0.1 the main website wants everyone to download 8.

**Comment by EmilyBjoerk** [comment]
As of next release Java 8 should be minimum version needed.
