### ISSUE TITLE
32 bit LSML but no 32 bit Java 9.0.1

### ISSUE THREAD

**Issue by Smokey2** [EmilyBjoerk/lsml#726]
Java has no intention of creating a 32 bit version 9.

**Comment by EmilyBjoerk** [comment]
LSML should still run with Java 8 which [is available for 32 bit machines](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) still and [Microsoft offers 32 bit Windows 10 still](https://www.microsoft.com/en-gb/software-download/windows10). The installer for 64 bit wouldn't work for these users.
