### ISSUE TITLE
Building with Java 10 + Eclipse Photon supported?

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#730]
I've installed the latest Java dev tools, configured my JAVA_PATH and PATH to point to JDK 10. Ran `gradlew.bat`, that resulted in LSML starting up, so I assume everything went well. But after importing the project to Eclipse and setting it up as described on the Wiki I get 3781 errors, all of them seem to be related to Java FX. They are of this kind:

`The type 'Platform' is not API (restriction on required library 'C:\Program Files\Java\jre-10.0.1\lib\jrt-fs.jar')`

What should I do?

**Comment by EmilyBjoerk** [comment]
Yeah there seems to be some kind of bug here (I had it to), I had to go into project settings and set the project to use java 8. LSML will build on java 10 but targets java 8.

**Comment by EmilyBjoerk** [comment]
To clarify: A tooling bug. LSML still functions fine

**Comment by VioletGiraffe** [comment]
So there is no way to get it working with JDK 10, no matter what compatibility level?

**Comment by EmilyBjoerk** [comment]
I will likely push 2.0.9 to backers in 24h, I can get your fix into 2.0.9 if you can put a mergable PR together by then.

**Comment by VioletGiraffe** [comment]
Sorry, I don't have a multi-monitor setup at home, will only be able to look into it in the office on Monday (hopefully). So don't hold the much needed update on my account.

**Comment by VioletGiraffe** [comment]
>Trust me, you'll have so much less pain by simply installing jdk 8 -.-;

That works, and every project setting described on the Wiki is already set except for "Ignore optional compile problems".
