### ISSUE TITLE
Could not find stylesheet: bin/view/BaseStyle.css

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#732]
When running LSML from the freshly cloned and built repo, I see this:

![image](https://user-images.githubusercontent.com/1175926/42747831-9315af94-88e6-11e8-859c-2de08e4ecf78.png)

And I see this in the log: 
```
Jul 16, 2018 10:53:50 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not find stylesheet: file:/E:/tmp/lsml/bin/view/BaseStyle.css
```

**Comment by EmilyBjoerk** [comment]
Under `Java Build Path > Source > lsml/src/main/resources` remove from `excluded:` the value `**/*.xss`.

**Comment by EmilyBjoerk** [comment]
I don't know why that is added there in photon, it didn't use to be a problem and I haven't found a way to fix this yet.

**Comment by VioletGiraffe** [comment]
Doesn't seem to be on the Wiki. Worth adding to "Dev Env Setup"?
