### ISSUE TITLE
Engine drop-down ranges are displayed on a per-mech rather than per-variant basis

### ISSUE THREAD

**Issue by furkle** [EmilyBjoerk/lsml#733]
**Steps to reproduce issue:**
1. Open LSML
2. Create UrbanMech UM-R63 build 
3. Drag an XL engine of any size into the mech.
4. Use the drop-down to select any engine size lower than 100

**Actual result:**
An exception is thrown with the message `java.lang.RuntimeException: org.lisoft.lsml.model.NoSuchItemException: No item with name:XL ENGINE 90 at org.lisoft.lsml.view_fx.controls.EquippedItemCell.changeEngine(EquippedItemCell.java:210)`.

**Expected result:**
It should not be possible to select XL engine variants that do not exist. (My hypothesis is that this is caused by a code-side assumption that all mechs have the same available range of engines regardless of STD, LE, or XL type, which goofy mechs like the UM make unworkable.)

Thanks so much for the build tool, I've been having a ton of fun with it!

n.b. The same exception occurs when using the XL checkbox on a non-XL engine rated below 100.

**Comment by EmilyBjoerk** [comment]
Yeah the engine dropdown needs some tlc... it suffered a bit when I scrambled to get a fix out when they released the patch with the new engines and weapons.

I'll give it the once over for the next release.

**Comment by furkle** [comment]
Thanks so much Li Song!
